name: 'LiteCov'
description: 'Lightweight code coverage reporter - posts PR comments with coverage stats'
author: 'Manash Kumar Mandal'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  coverage-file:
    description: 'Path to coverage report file (auto-detected if not specified)'
    required: false
  format:
    description: 'Coverage format: auto, lcov, cobertura'
    required: false
    default: 'auto'
  show-files:
    description: 'Files to show: all, changed, threshold:N, worst:N'
    required: false
    default: 'changed'
  threshold:
    description: 'Minimum coverage threshold for passing status (0-100)'
    required: false
    default: '0'
  title:
    description: 'Comment title'
    required: false
    default: 'Coverage Report'
  annotations:
    description: 'Output GitHub annotations for uncovered lines'
    required: false
    default: 'false'
  base-coverage-file:
    description: 'Path to base branch coverage file for comparison'
    required: false
  base-branch:
    description: 'Base branch name for display in diff header'
    required: false
    default: 'main'
  token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}

outputs:
  coverage:
    description: 'Total coverage percentage'
  lines-covered:
    description: 'Number of covered lines'
  lines-total:
    description: 'Total number of lines'
  files-count:
    description: 'Number of files with coverage data'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    INPUT_COVERAGE_FILE: ${{ inputs.coverage-file }}
    INPUT_FORMAT: ${{ inputs.format }}
    INPUT_SHOW_FILES: ${{ inputs.show-files }}
    INPUT_THRESHOLD: ${{ inputs.threshold }}
    INPUT_TITLE: ${{ inputs.title }}
    INPUT_ANNOTATIONS: ${{ inputs.annotations }}
    INPUT_BASE_COVERAGE_FILE: ${{ inputs.base-coverage-file }}
    INPUT_BASE_BRANCH: ${{ inputs.base-branch }}
