package comment

import (
	"fmt"
	"sort"
	"strings"

	"github.com/litecov/litecov/internal/coverage"
)

const Marker = "<!-- litecov -->"

type Options struct {
	Title        string
	ShowFiles    string
	ChangedFiles []string
	Threshold    float64
	WorstN       int
}

func Format(report *coverage.Report, opts Options) string {
	var sb strings.Builder

	sb.WriteString(Marker)
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("## %s\n\n", opts.Title))

	sb.WriteString("| Metric | Value |\n")
	sb.WriteString("|--------|-------|\n")
	sb.WriteString(fmt.Sprintf("| **Coverage** | `%.2f%%` |\n", report.Coverage))
	sb.WriteString(fmt.Sprintf("| **Lines** | `%d/%d` |\n", report.TotalCovered, report.TotalLines))
	sb.WriteString(fmt.Sprintf("| **Files** | `%d` |\n", len(report.Files)))
	sb.WriteString("\n")

	filesToShow := filterFiles(report.Files, opts)

	if len(filesToShow) > 0 {
		sb.WriteString("| File | Coverage | |\n")
		sb.WriteString("|------|----------|---|\n")
		for _, f := range filesToShow {
			pct := f.Percentage()
			indicator := ""
			if pct < 50 {
				indicator = " :warning:"
			}
			sb.WriteString(fmt.Sprintf("| `%s` | `%.2f%%` |%s |\n", f.Path, pct, indicator))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("<sub>Generated by [LiteCov](https://github.com/litecov/litecov)</sub>\n")

	return sb.String()
}

func filterFiles(files []coverage.FileCoverage, opts Options) []coverage.FileCoverage {
	switch {
	case opts.ShowFiles == "all":
		return files

	case opts.ShowFiles == "changed":
		if len(opts.ChangedFiles) == 0 {
			return files
		}
		changedSet := make(map[string]bool)
		for _, f := range opts.ChangedFiles {
			changedSet[f] = true
		}
		var result []coverage.FileCoverage
		for _, f := range files {
			if changedSet[f.Path] {
				result = append(result, f)
			}
		}
		return result

	case strings.HasPrefix(opts.ShowFiles, "threshold:"):
		var result []coverage.FileCoverage
		for _, f := range files {
			if f.Percentage() < opts.Threshold {
				result = append(result, f)
			}
		}
		return result

	case strings.HasPrefix(opts.ShowFiles, "worst:"):
		sorted := make([]coverage.FileCoverage, len(files))
		copy(sorted, files)
		sort.Slice(sorted, func(i, j int) bool {
			return sorted[i].Percentage() < sorted[j].Percentage()
		})
		if opts.WorstN > len(sorted) {
			return sorted
		}
		return sorted[:opts.WorstN]

	default:
		return files
	}
}
